version: '3'
services:
    ecidade:
        build:
            context: ./docker
            dockerfile: Dockerfile
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-8080}:80'
        volumes:
            - './:/var/www/html'
        depends_on:
             - pgsql
        networks:
           - ecidade
    pgsql:
         image: 'postgres:14'
         ports:
             - '${DB_PORTA:-5432}:5432'
         environment:
             PGPASSWORD: '${DB_SENHA:-secret}'
             POSTGRES_DB: '${DB_BASE}'
             POSTGRES_USER: '${DB_USUARIO}'
             POSTGRES_PASSWORD: '${DB_SENHA:-secret}'
         volumes:
           - './docker/db-data:/var/lib/postgresql/data'
         networks:
           - ecidade
networks:
    ecidade:
         driver: bridge
