CREATE TABLE NFCES033 (
    CODORGEMIS VARCHAR(2),
    DESCRICAO VARCHAR(60));

INSERT INTO NFCES033 (CODORGEMIS, DESCRICAO) VALUES ('10', 'SSP - SECRETARIA DE SEGURANCA PUBLICA');
INSERT INTO NFCES033 (CODORGEMIS, DESCRICAO) VALUES ('41', 'COMANDO DA AERONAUTICA EX MIN AERONAUTICA');
INSERT INTO NFCES033 (CODORGEMIS, DESCRICAO) VALUES ('42', 'COMANDO DO EXERCITO EX MIN EXERCITO');
INSERT INTO NFCES033 (CODORGEMIS, DESCRICAO) VALUES ('43', 'COMANDO DA MARINHA EX MIN MARINHA');
INSERT INTO NFCES033 (CODORGEMIS, DESCRICAO) VALUES ('44', 'POLICIA FEDERAL');
INSERT INTO NFCES033 (CODORGEMIS, DESCRICAO) VALUES ('60', 'CARTEIRA DE IDENTIDADE CLASSISTA');
INSERT INTO NFCES033 (CODORGEMIS, DESCRICAO) VALUES ('61', 'ADMINISTRACAO CONSELHO REGIONAL');
INSERT INTO NFCES033 (CODORGEMIS, DESCRICAO) VALUES ('62', 'ASSISTENCIA SOCIAL CONSELHO REGIONAL');
INSERT INTO NFCES033 (CODORGEMIS, DESCRICAO) VALUES ('63', 'BIBLIOTECONOMIA CONSELHO REGIONAL');
INSERT INTO NFCES033 (CODORGEMIS, DESCRICAO) VALUES ('64', 'CONTABILIDADE CONSELHO REGIONAL');
INSERT INTO NFCES033 (CODORGEMIS, DESCRICAO) VALUES ('65', 'CORRETORES DE IMOVEIS CONSELHO REGIONAL');
INSERT INTO NFCES033 (CODORGEMIS, DESCRICAO) VALUES ('66', 'ENFERMAGEM CONSELHO REGIONAL');
INSERT INTO NFCES033 (CODORGEMIS, DESCRICAO) VALUES ('67', 'ENGENHARIA,ARQ E AGRONOMIA - CONSELHO REGIONAL');
INSERT INTO NFCES033 (CODORGEMIS, DESCRICAO) VALUES ('68', 'ESTATISTICA CONSELHO REGIONAL');
INSERT INTO NFCES033 (CODORGEMIS, DESCRICAO) VALUES ('69', 'FARMACIA CONSELHO REGIONAL');
INSERT INTO NFCES033 (CODORGEMIS, DESCRICAO) VALUES ('70', 'FISIOTERAPIA E TERAPIA OCUP CONSELHO REGIONAL');
INSERT INTO NFCES033 (CODORGEMIS, DESCRICAO) VALUES ('71', 'MEDICINA CONSELHO REGIONAL');
INSERT INTO NFCES033 (CODORGEMIS, DESCRICAO) VALUES ('72', 'MEDICINA VETERINARIA CONSELHO REGIONAL');
INSERT INTO NFCES033 (CODORGEMIS, DESCRICAO) VALUES ('73', 'MUSICOS DO BRASIL ORDEM');
INSERT INTO NFCES033 (CODORGEMIS, DESCRICAO) VALUES ('74', 'NUTRICAO CONSELHO REGIONAL');
INSERT INTO NFCES033 (CODORGEMIS, DESCRICAO) VALUES ('75', 'ODONTOLOGIA CONSELHO REGIONAL');
INSERT INTO NFCES033 (CODORGEMIS, DESCRICAO) VALUES ('76', 'RELACOES PUBLICAS CONSELHO REGIONAL');
INSERT INTO NFCES033 (CODORGEMIS, DESCRICAO) VALUES ('77', 'PSICOLOGIA CONSELHO REGIONAL');
INSERT INTO NFCES033 (CODORGEMIS, DESCRICAO) VALUES ('78', 'QUIMICA CONSELHO REGIONAL');
INSERT INTO NFCES033 (CODORGEMIS, DESCRICAO) VALUES ('79', 'REPRESENTANTES COMERCIAIS CONSELHO REGIONAL');
INSERT INTO NFCES033 (CODORGEMIS, DESCRICAO) VALUES ('80', 'ADVOGADOS DO BRASIL ORDEM');
INSERT INTO NFCES033 (CODORGEMIS, DESCRICAO) VALUES ('81', 'OUTROS EMISSORES');
INSERT INTO NFCES033 (CODORGEMIS, DESCRICAO) VALUES ('82', 'DOCUMENTO ESTRANGEIRO');
INSERT INTO NFCES033 (CODORGEMIS, DESCRICAO) VALUES ('99', NULL);
INSERT INTO NFCES033 (CODORGEMIS, DESCRICAO) VALUES ('40', 'ORGANISMOS MILITARES');
INSERT INTO NFCES033 (CODORGEMIS, DESCRICAO) VALUES ('18', 'CR BIOLOGIA');
INSERT INTO NFCES033 (CODORGEMIS, DESCRICAO) VALUES ('15', 'CR BIOMEDICINA');
INSERT INTO NFCES033 (CODORGEMIS, DESCRICAO) VALUES ('25', 'CR DE OPTICOS');
INSERT INTO NFCES033 (CODORGEMIS, DESCRICAO) VALUES ('26', 'CR DE TECNICOS DE RADIOLOGIA');
INSERT INTO NFCES033 (CODORGEMIS, DESCRICAO) VALUES ('20', 'CR ECONOMIA');
INSERT INTO NFCES033 (CODORGEMIS, DESCRICAO) VALUES ('19', 'CR EDUCACAO FISICA');
INSERT INTO NFCES033 (CODORGEMIS, DESCRICAO) VALUES ('22', 'CR FISICA');
INSERT INTO NFCES033 (CODORGEMIS, DESCRICAO) VALUES ('17', 'CR FONOAUDIOLOGIA');
INSERT INTO NFCES033 (CODORGEMIS, DESCRICAO) VALUES ('24', 'CR PEDAGOGO');
INSERT INTO NFCES033 (CODORGEMIS, DESCRICAO) VALUES ('23', 'CR RADIOLOGIA');
INSERT INTO NFCES033 (CODORGEMIS, DESCRICAO) VALUES ('12', 'OAB');

COMMIT WORK;
