CREATE TABLE NFCES012 (
    COD_PROG VARCHAR(2),
    DESCRICAO VARCHAR(60),
    TP_PROG CHAR(1));

INSERT INTO NFCES012 (COD_PROG, DESCRICAO, TP_PROG) VALUES ('01', 'ATENCAO BASICA', '1');
INSERT INTO NFCES012 (COD_PROG, DESCRICAO, TP_PROG) VALUES ('02', 'MEDIA COMPLEXIDADE', '1');
INSERT INTO NFCES012 (COD_PROG, DESCRICAO, TP_PROG) VALUES ('03', 'INTERNACAO', '2');
INSERT INTO NFCES012 (COD_PROG, DESCRICAO, TP_PROG) VALUES ('04', 'ALTA COMPLEXIDADE', '1');
INSERT INTO NFCES012 (COD_PROG, DESCRICAO, TP_PROG) VALUES ('05', 'MEDIA COMPLEXIDADE', '2');
INSERT INTO NFCES012 (COD_PROG, DESCRICAO, TP_PROG) VALUES ('06', 'ALTA COMPLEXIDADE', '2');

COMMIT WORK;
