CREATE TABLE NFCES003 (
    COD_CONVEN VARCHAR(2),
    DESCRICAO VARCHAR(60));

INSERT INTO NFCES003 (COD_CONVEN, DESCRICAO) VALUES ('01', 'SUS');
INSERT INTO NFCES003 (COD_CONVEN, DESCRICAO) VALUES ('02', 'PARTICULAR');
INSERT INTO NFCES003 (COD_CONVEN, DESCRICAO) VALUES ('05', 'PLANO DE SAUDE PUBLICO');
INSERT INTO NFCES003 (COD_CONVEN, DESCRICAO) VALUES ('06', 'PLANO DE SAUDE PRIVADO');

COMMIT WORK;
