CREATE TABLE NFCES058 (
    CD_VINCULACAO VARCHAR(2),
    TP_VINCULO VARCHAR(2),
    TP_SUBVINCULO VARCHAR(2),
    DS_SUBVINCULO VARCHAR(60));

INSERT INTO NFCES058 (CD_VINCULACAO, TP_VINCULO, TP_SUBVINCULO, DS_SUBVINCULO) VALUES ('01', '01', '00', 'SEM SUBTIPO');
INSERT INTO NFCES058 (CD_VINCULACAO, TP_VINCULO, TP_SUBVINCULO, DS_SUBVINCULO) VALUES ('01', '02', '00', 'SEM SUBTIPO');
INSERT INTO NFCES058 (CD_VINCULACAO, TP_VINCULO, TP_SUBVINCULO, DS_SUBVINCULO) VALUES ('01', '03', '00', 'SEM SUBTIPO');
INSERT INTO NFCES058 (CD_VINCULACAO, TP_VINCULO, TP_SUBVINCULO, DS_SUBVINCULO) VALUES ('01', '04', '00', 'SEM SUBTIPO');
INSERT INTO NFCES058 (CD_VINCULACAO, TP_VINCULO, TP_SUBVINCULO, DS_SUBVINCULO) VALUES ('01', '05', '01', 'CONTRATO POR OSCIP/OS');
INSERT INTO NFCES058 (CD_VINCULACAO, TP_VINCULO, TP_SUBVINCULO, DS_SUBVINCULO) VALUES ('01', '05', '02', 'CONTRATO POR ONG');
INSERT INTO NFCES058 (CD_VINCULACAO, TP_VINCULO, TP_SUBVINCULO, DS_SUBVINCULO) VALUES ('01', '05', '03', 'CONTRATO POR ENTIDADE FILANTROPICA');
INSERT INTO NFCES058 (CD_VINCULACAO, TP_VINCULO, TP_SUBVINCULO, DS_SUBVINCULO) VALUES ('01', '05', '04', 'CONTRATO POR REDE PRIVADA');
INSERT INTO NFCES058 (CD_VINCULACAO, TP_VINCULO, TP_SUBVINCULO, DS_SUBVINCULO) VALUES ('02', '00', '00', 'SEM SUBTIPO');
INSERT INTO NFCES058 (CD_VINCULACAO, TP_VINCULO, TP_SUBVINCULO, DS_SUBVINCULO) VALUES ('03', '00', '00', 'SEM SUBTIPO');
INSERT INTO NFCES058 (CD_VINCULACAO, TP_VINCULO, TP_SUBVINCULO, DS_SUBVINCULO) VALUES ('04', '01', '00', 'SEM SUBTIPO');
INSERT INTO NFCES058 (CD_VINCULACAO, TP_VINCULO, TP_SUBVINCULO, DS_SUBVINCULO) VALUES ('04', '02', '00', 'SEM SUBTIPO');

COMMIT WORK;
