CREATE TABLE NFCES056 (
    CD_VINCULACAO VARCHAR(2),
    DS_VINCULACAO VARCHAR(60));

INSERT INTO NFCES056 (CD_VINCULACAO, DS_VINCULACAO) VALUES ('01', 'VINCULO EMPREGATICIO');
INSERT INTO NFCES056 (CD_VINCULACAO, DS_VINCULACAO) VALUES ('02', 'AUTONOMO');
INSERT INTO NFCES056 (CD_VINCULACAO, DS_VINCULACAO) VALUES ('03', 'COOPERATIVA');
INSERT INTO NFCES056 (CD_VINCULACAO, DS_VINCULACAO) VALUES ('04', 'OUTROS');

COMMIT WORK;
