CREATE TABLE NFCES008 (
    COD_NATORG VARCHAR(2),
    DESCRICAO VARCHAR(60));

INSERT INTO NFCES008 (COD_NATORG, DESCRICAO) VALUES ('01', 'ADMINISTRACAO DIRETA DA SAUDE (MS,SES E SMS)');
INSERT INTO NFCES008 (COD_NATORG, DESCRICAO) VALUES ('02', 'ADMINISTRACAO DIRETA DE OUTROS ORGAOS (MEC,MEX,MARINHA,ETC');
INSERT INTO NFCES008 (COD_NATORG, DESCRICAO) VALUES ('03', 'ADMINISTRACAO INDIRETA - AUTARQUIAS');
INSERT INTO NFCES008 (COD_NATORG, DESCRICAO) VALUES ('04', 'ADMINISTRACAO INDIRETA - FUNDACAO PUBLICA');
INSERT INTO NFCES008 (COD_NATORG, DESCRICAO) VALUES ('05', 'ADMINISTRACAO INDIRETA - EMPRESA PUBLICA');
INSERT INTO NFCES008 (COD_NATORG, DESCRICAO) VALUES ('06', 'ADMINISTRACAO INDIRETA - ORGANIZACAO SOCIAL PUBLICA');
INSERT INTO NFCES008 (COD_NATORG, DESCRICAO) VALUES ('07', 'EMPRESA PRIVADA');
INSERT INTO NFCES008 (COD_NATORG, DESCRICAO) VALUES ('08', 'FUNDACAO PRIVADA');
INSERT INTO NFCES008 (COD_NATORG, DESCRICAO) VALUES ('09', 'COOPERATIVA');
INSERT INTO NFCES008 (COD_NATORG, DESCRICAO) VALUES ('10', 'SERVICO SOCIAL AUTONOMO');
INSERT INTO NFCES008 (COD_NATORG, DESCRICAO) VALUES ('11', 'ENTIDADE BENEFICENTE SEM FINS LUCRATIVOS');
INSERT INTO NFCES008 (COD_NATORG, DESCRICAO) VALUES ('12', 'ECONOMIA MISTA');
INSERT INTO NFCES008 (COD_NATORG, DESCRICAO) VALUES ('13', 'SINDICATO');

COMMIT WORK;
