CREATE TABLE NFCES011 (
    COD_TURNAT VARCHAR(2),
    DESCRICAO VARCHAR(100));

INSERT INTO NFCES011 (COD_TURNAT, DESCRICAO) VALUES ('01', 'ATENDIMENTO SOMENTE PELA MANHA');
INSERT INTO NFCES011 (COD_TURNAT, DESCRICAO) VALUES ('02', 'ATENDIMENTO SOMENTE A TARDE');
INSERT INTO NFCES011 (COD_TURNAT, DESCRICAO) VALUES ('03', 'ATENDIMENTOS NOS TURNOS DA MANHA E A TARDE');
INSERT INTO NFCES011 (COD_TURNAT, DESCRICAO) VALUES ('04', 'ATENDIMENTO NOS TURNOS DA MANHA, TARDE E NOITE');
INSERT INTO NFCES011 (COD_TURNAT, DESCRICAO) VALUES ('05', 'ATENDIMENTO COM TURNOS INTERMITENTES');
INSERT INTO NFCES011 (COD_TURNAT, DESCRICAO) VALUES ('06', 'ATENDIMENTO CONTINUO DE 24 HORAS/DIA (PLANTAO: INCLUI SABADOS DOMINGOS E FERIADOS)');

COMMIT WORK;
