CREATE TABLE NFCES004 (
    CODATPREST VARCHAR(2),
    DESCRICAO VARCHAR(60));

INSERT INTO NFCES004 (CODATPREST, DESCRICAO) VALUES ('01', 'INTERNACAO');
INSERT INTO NFCES004 (CODATPREST, DESCRICAO) VALUES ('02', 'AMBULATORIAL');
INSERT INTO NFCES004 (CODATPREST, DESCRICAO) VALUES ('03', 'SADT');
INSERT INTO NFCES004 (CODATPREST, DESCRICAO) VALUES ('04', 'URGENCIA');
INSERT INTO NFCES004 (CODATPREST, DESCRICAO) VALUES ('05', 'OUTROS');
INSERT INTO NFCES004 (CODATPREST, DESCRICAO) VALUES ('06', 'VIGILANCIA EM SAUDE');
INSERT INTO NFCES004 (CODATPREST, DESCRICAO) VALUES ('07', 'REGULACAO');

COMMIT WORK;
