CREATE TABLE NFCES030 (
    CODRET VARCHAR(2),
    SITUACAO VARCHAR(60));

INSERT INTO NFCES030 (CODRET, SITUACAO) VALUES ('10', 'UNIDADE PUBLICA');
INSERT INTO NFCES030 (CODRET, SITUACAO) VALUES ('11', 'UNIDADE FILANTROPICA');
INSERT INTO NFCES030 (CODRET, SITUACAO) VALUES ('12', 'UNIDADE SEM FINS LUCRATIVOS');
INSERT INTO NFCES030 (CODRET, SITUACAO) VALUES ('13', 'UNIDADE PRIVADA LUCRATIVA  SIMPLES');
INSERT INTO NFCES030 (CODRET, SITUACAO) VALUES ('14', 'UNIDADE PRIVADA LUCRATIVA');
INSERT INTO NFCES030 (CODRET, SITUACAO) VALUES ('15', 'UNIDADE SINDICAL');
INSERT INTO NFCES030 (CODRET, SITUACAO) VALUES ('16', 'UNIDADE PESSOA FISICA');

COMMIT WORK;
