CREATE TABLE NFCES057 (
    CD_VINCULACAO VARCHAR(2),
    TP_VINCULO VARCHAR(2),
    DS_VINCULO VARCHAR(60),
    TP_ESFADM VARCHAR(20));

INSERT INTO NFCES057 (CD_VINCULACAO, TP_VINCULO, DS_VINCULO, TP_ESFADM) VALUES ('01', '00', 'SEM TIPO', '');
INSERT INTO NFCES057 (CD_VINCULACAO, TP_VINCULO, DS_VINCULO, TP_ESFADM) VALUES ('01', '01', 'ESTATUTARIO', '01;02;03');
INSERT INTO NFCES057 (CD_VINCULACAO, TP_VINCULO, DS_VINCULO, TP_ESFADM) VALUES ('01', '02', 'EMPREGO PUBLICO', '01;02;03');
INSERT INTO NFCES057 (CD_VINCULACAO, TP_VINCULO, DS_VINCULO, TP_ESFADM) VALUES ('01', '03', 'CONTRATO POR PRAZO DETERMINADO', '01;02;03;04');
INSERT INTO NFCES057 (CD_VINCULACAO, TP_VINCULO, DS_VINCULO, TP_ESFADM) VALUES ('01', '04', 'CARGO COMISSIONADO', '01;02;03');
INSERT INTO NFCES057 (CD_VINCULACAO, TP_VINCULO, DS_VINCULO, TP_ESFADM) VALUES ('01', '05', 'CELETISTA', '04');
INSERT INTO NFCES057 (CD_VINCULACAO, TP_VINCULO, DS_VINCULO, TP_ESFADM) VALUES ('02', '00', 'SEM TIPO', '');
INSERT INTO NFCES057 (CD_VINCULACAO, TP_VINCULO, DS_VINCULO, TP_ESFADM) VALUES ('03', '00', 'SEM TIPO', '');
INSERT INTO NFCES057 (CD_VINCULACAO, TP_VINCULO, DS_VINCULO, TP_ESFADM) VALUES ('04', '01', 'BOLSA', '01;02;03;04');
INSERT INTO NFCES057 (CD_VINCULACAO, TP_VINCULO, DS_VINCULO, TP_ESFADM) VALUES ('04', '02', 'CONTRATO VERBAL/INFORMAL', '01;02;03;04');

COMMIT WORK;
