CREATE TABLE NFCES002 (
    COD_CLIENT VARCHAR(2),
    DESCRICAO VARCHAR(60));

INSERT INTO NFCES002 (COD_CLIENT, DESCRICAO) VALUES ('01', 'ATENDIMENTO DE DEMANDA ESPONTANEA');
INSERT INTO NFCES002 (COD_CLIENT, DESCRICAO) VALUES ('02', 'ATENDIMENTO DE DEMANDA REFERENCIADA');
INSERT INTO NFCES002 (COD_CLIENT, DESCRICAO) VALUES ('03', 'ATENDIMENTO DE DEMANDA ESPONTANEA E REFERENCIADA');

COMMIT WORK;
