CREATE TABLE NFCES006 (
    COD_ESFADM VARCHAR(2),
    DESCRICAO VARCHAR(60));

INSERT INTO NFCES006 (COD_ESFADM, DESCRICAO) VALUES ('01', 'FEDERAL');
INSERT INTO NFCES006 (COD_ESFADM, DESCRICAO) VALUES ('02', 'ESTADUAL');
INSERT INTO NFCES006 (COD_ESFADM, DESCRICAO) VALUES ('03', 'MUNICIPAL');
INSERT INTO NFCES006 (COD_ESFADM, DESCRICAO) VALUES ('04', 'PRIVADA');

COMMIT WORK;
