CREATE TABLE NFCES010 (
    TP_UNID_ID VARCHAR(2),
    DESCRICAO VARCHAR(60));

INSERT INTO NFCES010 (TP_UNID_ID, DESCRICAO) VALUES ('01', 'POSTO DE SAUDE');
INSERT INTO NFCES010 (TP_UNID_ID, DESCRICAO) VALUES ('02', 'CENTRO DE SAUDE/UNIDADE BASICA');
INSERT INTO NFCES010 (TP_UNID_ID, DESCRICAO) VALUES ('04', 'POLICLINICA');
INSERT INTO NFCES010 (TP_UNID_ID, DESCRICAO) VALUES ('05', 'HOSPITAL GERAL');
INSERT INTO NFCES010 (TP_UNID_ID, DESCRICAO) VALUES ('07', 'HOSPITAL ESPECIALIZADO');
INSERT INTO NFCES010 (TP_UNID_ID, DESCRICAO) VALUES ('15', 'UNIDADE MISTA');
INSERT INTO NFCES010 (TP_UNID_ID, DESCRICAO) VALUES ('20', 'PRONTO SOCORRO GERAL');
INSERT INTO NFCES010 (TP_UNID_ID, DESCRICAO) VALUES ('21', 'PRONTO SOCORRO ESPECIALIZADO');
INSERT INTO NFCES010 (TP_UNID_ID, DESCRICAO) VALUES ('22', 'CONSULTORIO ISOLADO');
INSERT INTO NFCES010 (TP_UNID_ID, DESCRICAO) VALUES ('32', 'UNIDADE MOVEL FLUVIAL');
INSERT INTO NFCES010 (TP_UNID_ID, DESCRICAO) VALUES ('36', 'CLINICA ESPECIALIZADA/AMBULATORIO DE ESPECIALIDADE');
INSERT INTO NFCES010 (TP_UNID_ID, DESCRICAO) VALUES ('39', 'UNIDADE DE APOIO DIAGNOSE E TERAPIA (SADT ISOLADO)');
INSERT INTO NFCES010 (TP_UNID_ID, DESCRICAO) VALUES ('40', 'UNIDADE MOVEL TERRESTRE');
INSERT INTO NFCES010 (TP_UNID_ID, DESCRICAO) VALUES ('42', 'UNIDADE MOVEL DE NIVEL PRE-HOSP URGENCIA/EMERGENCIA');
INSERT INTO NFCES010 (TP_UNID_ID, DESCRICAO) VALUES ('43', 'FARMACIA');
INSERT INTO NFCES010 (TP_UNID_ID, DESCRICAO) VALUES ('50', 'UNIDADE DE VIGILANCIA EM SAUDE');
INSERT INTO NFCES010 (TP_UNID_ID, DESCRICAO) VALUES ('60', 'COOPERATIVA');
INSERT INTO NFCES010 (TP_UNID_ID, DESCRICAO) VALUES ('61', 'CENTRO DE PARTO NORMAL - ISOLADO');
INSERT INTO NFCES010 (TP_UNID_ID, DESCRICAO) VALUES ('62', 'HOSPITAL/DIA - ISOLADO');
INSERT INTO NFCES010 (TP_UNID_ID, DESCRICAO) VALUES ('64', 'CENTRAL DE REGULACAO DE SERVICOS DE SAUDE');
INSERT INTO NFCES010 (TP_UNID_ID, DESCRICAO) VALUES ('67', 'LABORATORIO CENTRAL DE SAUDE PUBLICA - LACEN');
INSERT INTO NFCES010 (TP_UNID_ID, DESCRICAO) VALUES ('68', 'SECRETARIA DE SAUDE');
INSERT INTO NFCES010 (TP_UNID_ID, DESCRICAO) VALUES ('69', 'CENTRO DE ATENCAO HEMOTERAPICA E OU HEMATOLOGICA');
INSERT INTO NFCES010 (TP_UNID_ID, DESCRICAO) VALUES ('70', 'CENTRO DE ATENCAO PSICOSSOCIAL');
INSERT INTO NFCES010 (TP_UNID_ID, DESCRICAO) VALUES ('71', 'CENTRO DE APOIO A SAUDE DA FAMILIA');

COMMIT WORK;
