CREATE TABLE NFCES007 (
    COD_ATIVID VARCHAR(2),
    DESCRICAO VARCHAR(60));

INSERT INTO NFCES007 (COD_ATIVID, DESCRICAO) VALUES ('01', 'UNIDADE UNIVERSITARIA');
INSERT INTO NFCES007 (COD_ATIVID, DESCRICAO) VALUES ('02', 'UNIDADE ESCOLA SUPERIOR ISOLADA');
INSERT INTO NFCES007 (COD_ATIVID, DESCRICAO) VALUES ('03', 'UNIDADE AUXILIAR DE ENSINO');
INSERT INTO NFCES007 (COD_ATIVID, DESCRICAO) VALUES ('04', 'UNIDADE SEM ATIVIDADE DE ENSINO');
INSERT INTO NFCES007 (COD_ATIVID, DESCRICAO) VALUES ('05', 'HOSPITAL DE ENSINO');

COMMIT WORK;
