CREATE TABLE NFCES009 (
    CODNIVHIER VARCHAR(2),
    DESCRICAO VARCHAR(60));

INSERT INTO NFCES009 (CODNIVHIER, DESCRICAO) VALUES ('01', 'PAB-PABA');
INSERT INTO NFCES009 (CODNIVHIER, DESCRICAO) VALUES ('02', 'MEDIA - M1');
INSERT INTO NFCES009 (CODNIVHIER, DESCRICAO) VALUES ('03', 'MEDIA - M2 E M3');
INSERT INTO NFCES009 (CODNIVHIER, DESCRICAO) VALUES ('04', 'ALTA AMB');
INSERT INTO NFCES009 (CODNIVHIER, DESCRICAO) VALUES ('05', 'BAIXA - M1 E M2');
INSERT INTO NFCES009 (CODNIVHIER, DESCRICAO) VALUES ('06', 'MEDIA - M2 E M3');
INSERT INTO NFCES009 (CODNIVHIER, DESCRICAO) VALUES ('07', 'MEDIA - M3');
INSERT INTO NFCES009 (CODNIVHIER, DESCRICAO) VALUES ('08', 'ALTA HOSP/AMB');

COMMIT WORK;
